version: '3'
services:
  postgres:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgresql/initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  migrate:
    build:
      context: ./migrate/
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./migrate/db/migrations/:/opt/migrate/db/migrations/
      - ./migrate/Makefile:/opt/migrate/Makefile
    environment:
      - POSTGRESQL_URL="postgres://postgres:postgres@postgres:5432/go_todo_app_${GO_ENV}?sslmode=disable"

  prism:
    image: stoplight/prism:4.10.3
    command: 'mock -h 0.0.0.0 -p 8081 /tmp/openapi.yaml'
    volumes:
      - ./reference/openapi.yaml:/tmp/openapi.yaml
    ports:
      - '8081:8081'

volumes:
  db_data:
