version: '3'
services:
  postgres:
    image: postgres:13.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgresql/initdb:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data

  migrate:
    build:
      context: ./migrate/
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./migrate/db/migrations/:/opt/migrate/db/migrations/
      - ./migrate/Makefile:/opt/migrate/Makefile
    environment:
      - POSTGRESQL_URL="postgres://postgres:postgres@postgres:5432/go_todo_app_${GO_ENV}?sslmode=disable"

  web:
    build:
      context: .
      target: runner
    volumes:
      - ./src/:/opt/myapp/
    working_dir: /opt/myapp/cmd
    ports:
      - 8080:8080
    environment:
      - POSTGRESQL_URL="postgres://postgres:postgres@postgres:5432/go_todo_app_${GO_ENV}?sslmode=disable"
    command: go run main.go

volumes:
  db_data:
